### ISSUE TITLE
Last request mode

### ISSUE THREAD

**Issue by DJanocha** [enkot/querio#10]
Is it possible to add a togglable mode during which the newest request is automatically selected?
Sometimes one needs to inspect one request multiple times in different circumstances.
That toggler would help a ton.

In my opinion the best place to put the toggler icon would be next  to the 'Clear' icon
![image](https://user-images.githubusercontent.com/50969285/177951104-59ec19e1-750c-4d48-89f3-dccb389d1c9c.png)

or somewhere in the settings modal 
![image](https://user-images.githubusercontent.com/50969285/177951414-a1ef5491-c420-4c65-9317-25d27356bfb3.png)

**Comment by asingh04** [comment]
In my opinion, there should be a "Sort" button besides the "FIlter" text bar, which could be a toggle type

<img width="606" alt="image" src="https://user-images.githubusercontent.com/15160343/191305356-d5f79a64-5e98-4c5d-9700-b4bff2afda61.png">
