### ISSUE TITLE
No requests show in GQL

### ISSUE THREAD

**Issue by nicoabie** [enkot/querio#12]
What info can I provide to debug this?

![image](https://user-images.githubusercontent.com/2797992/220374646-339d65c8-9b6b-4cf2-b571-a90e05dd9d48.png)
![image](https://user-images.githubusercontent.com/2797992/220374724-2c92874f-862a-43c7-a132-44e42a890806.png)

**Comment by enkot** [comment]
Hi @nicoabie,
Can you please provide the HAR file with the info about your requests?

**Comment by nicoabie** [comment]
I detected the issue is that it does not show the requests that are done on page load without user interaction. 

Do you still need the HAR file?

**Comment by nathanchapman** [comment]
@nicoabie are you using [query batching](https://www.apollographql.com/docs/kotlin/advanced/query-batching/)?

I'm noticing that GraphQL requests don't show up in Querio if they contain batched queries/mutations. Queries sent solo (without batching) do appear in Querio.

Trying to determine if this is your same issue or if I should open up a new issue

**Comment by nicoabie** [comment]
Hi @nathanchapman sometimes we do use it so this could be definitely related. 

I noticed that queries do not appear on load which is when we normally batch them and then they start to appear.

My gut tell me it is exactly what you are referring to, to be an issue with batching and not initial load.

I'll advise you to create a new issue with batching in the title and link this one so it has more visibility. Thanks for reaching out and good finding!

**Comment by nathanchapman** [comment]
@nicoabie I figured this may be the case!
