### ISSUE TITLE
Feature Request: Prettify/Indent the queries, mutations and subscriptions in the inspector

### ISSUE THREAD

**Issue by asingh04** [enkot/querio#2]
There should an option to prettify/indent a query/mutation/subscription when viewing it in the inspector. Most of the time the queries used by the client is minified or without identation. This makes the query difficult to read in the inspector as well.

Would be happy to work on this as well.

**Comment by enkot** [comment]
Hi @asingh04,

Nice idea, if you can work on that, would be great :)

**Comment by asingh04** [comment]
#3

**Comment by asingh04** [comment]
#3

**Comment by asingh04** [comment]
@enkot When will this feature be released?
